### ISSUE TITLE
about shadows

### ISSUE THREAD

**Issue by beyazit** [thisisroi/serene-theme#1]
I can't separate it because it has (almost) no shadow

<img width="1103" alt="Screenshot 2023-02-28 at 4 22 26 PM" src="https://user-images.githubusercontent.com/79628065/221866583-4b315c20-530d-4469-8569-a28d9213034b.png">

**Comment by ali-furkan** [comment]
Does it really seem so ??

**Comment by thisisroi** [comment]
thanks, solved.
